### ISSUE TITLE
Compile-time issue on non-x86 arches

### ISSUE THREAD

**Issue by lemenkov** [OpenSIPS/opensips#1562]
Hello!

Sorry for being so late but I've just spotted that. All 2.4.x releases cannot be compiled on non-x86 arches. This is how it looks (ver. 2.4.3):

* https://koji.fedoraproject.org/koji/taskinfo?taskID=31390226

* https://kojipkgs.fedoraproject.org//work/tasks/233/31390233/build.log (x86_64 build log - successful)
* https://kojipkgs.fedoraproject.org//work/tasks/234/31390234/build.log (ppc64le build log - unsuccessful)

The issue was first introduced with commit 091149b07902cf770618a9715e6738b9c2714fe5 and it looked slightly different back then:

* https://koji.fedoraproject.org/koji/taskinfo?taskID=31404401

* https://kojipkgs.fedoraproject.org//work/tasks/4402/31404402/build.log (x86_64 build log - successful)
* https://kojipkgs.fedoraproject.org//work/tasks/4403/31404403/build.log (ppc64le build log - unsuccessful)

Note the following message on non-x86 arches - I guess this is where all troubles have started:

```
In file included from mem/../mem/../globals.h:30,
                 from mem/../mem/shm_mem.h:54,
                 from mem/../lock_alloc.h:55,
                 from mem/../locking.h:66,
                 from mem/../statistics.h:154,
                 from mem/../pt_load.h:25,
                 from mem/../pt.h:34,
                 from mem/../dprint.h:55,
                 from mem/mem.h:38,
                 from mod_fix.c:30:
mem/../mem/../ip_addr.h: In function 'sockaddr2ip_addr':
mem/../mem/../ip_addr.h:233:4: warning: implicit declaration of function 'LM_CRIT'; did you mean 'LOG_CRIT'? [-Wimplicit-function-declaration]
    LM_CRIT("unknown address family %d\n", sa->sa_family);
    ^~~~~~~
    LOG_CRIT
```

Looks like something is going wrong with headers including. This all starts since commit 091149b07902cf770618a9715e6738b9c2714fe5 which looks fine to me.

These logs might get purged soon (in a week or so), so please ping me if they are gone - I'll rebuild it.

**Comment by bogdan-iancu** [comment]
@lemenkov , many thanks for the report. Please pull the latest 2.4.x version and give it a try.
There is an original fix b90a34c54bf747958544c66502f406cc4b935fb6, with 2 follows up 99f306a5d63e4826fe82891355e15d54da71842b and c4578e1503baf921d2a1ca813999b83538b79673.

Let me know if the fix holds !

**Comment by lemenkov** [comment]
A build log with these patches applied on top of 2.4.3:

* https://koji.fedoraproject.org/koji/taskinfo?taskID=31408293

**Comment by bogdan-iancu** [comment]
Thank you @lemenkov , I wanted to be sure the fix works before porting it further. I will do it right now.

**Comment by bogdan-iancu** [comment]
Ported to master also, closing
