### ISSUE TITLE
opensips-1.11.9 fails to build with OpenSSL-1.1.0

### ISSUE THREAD

**Issue by ppisar** [OpenSIPS/opensips#996]
Building opensips with OpenSSL 1.1.0c results in this error:

```
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fgnu89-inline -Wcast-align  -I/usr/include/json-c -DPKG_MALLOC  -DSHM_MEM  -DSHM_MMAP  -DUSE_IPV6  -DUSE_MCAST  -DDISABLE_NAGLE  -DSTATISTICS  -DCHANGEABLE_DEBUG_LEVEL  -DHAVE_RESOLV_RES  -DF_MALLOC  -DUSE_TCP   -DNAME='"opensips"' -DVERSION='"1.11.8-tls"' -DARCH='"x86_64"' -DOS='"linux"' -DCOMPILER='"gcc 6.2.1"' -D__CPU_x86_64 -D__OS_linux -D__SMP_yes -DCFG_DIR='"/etc/opensips/"'  -DUSE_FREERADIUS -DUSE_TLS -DFAST_LOCK -DADAPTIVE_WAIT -DADAPTIVE_WAIT_LOOPS=1024  -DHAVE_GETHOSTBYNAME2 -DHAVE_UNION_SEMUN -DHAVE_SCHED_YIELD -DHAVE_MSG_NOSIGNAL -DHAVE_MSGHDR_MSG_CONTROL -DHAVE_ALLOCA_H -DHAVE_TIMEGM -DHAVE_EPOLL -DHAVE_SIGIO_RT -DHAVE_SELECT -I/usr/ssl/include -I/usr/include -I/usr/include/openssl -c tls/tls_server.c -o tls/tls_server.o
[...]
tls/tls_server.c: In function 'tls_accept':
tls/tls_server.c:232:10: error: dereferencing pointer to incomplete type 'SSL {aka struct ssl_st}'
  if ( ssl->kssl_ctx==NULL )
          ^~
```

Openssl 1.1.0 made the SSL structure opaque and removed kssl.h header file.

**Comment by razvancrainea** [comment]
@ppisar I've just added support for the master branch. Could you take that code and give it a try?

**Comment by ppisar** [comment]
On Tue, Nov 29, 2016 at 04:18:20AM -0800, Răzvan Crainea wrote:
> I've just added support for the master branch. Could you take that
> code and give it a try?
> 
Thank you for the very quick response. I tried to compile the master branch.
The compilation proceeded futher, but failed in modules/identity/identity.c on
EVP_MD_CTX and X509_EXTENSION:

make[1]: Entering directory '/tmp/opensips/modules/identity'
Compiling identity.c
gcc -fPIC -DPIC -g -O0 -funroll-loops -Wcast-align -Wall -minline-all-stringops -falign-loops -ftree-vectorize -mtune=nocona -Wold-style-definition -Wmissing-field-initializers -Wredundant-decls -DMOD_NAME='identity'  -I/usr/include/json-c -DPKG_MALLOC  -DSHM_MMAP  -DUSE_MCAST  -DDISABLE_NAGLE  -DSTATISTICS  -DHAVE_RESOLV_RES  -DQM_MALLOC  -DDBG_MALLOC   -DNAME='"opensips"' -DVERSION='"2.3.0-dev"' -DARCH='"x86_64"' -DOS='"linux"' -DCOMPILER='"gcc 6.2.1"' -D__CPU_x86_64 -D__OS_linux -D__SMP_yes -DCFG_DIR='"/usr/local//etc/opensips/"'  -DVERSIONTYPE='"git"' -DTHISREVISION='"7151610"' -DFAST_LOCK -DADAPTIVE_WAIT -DADAPTIVE_WAIT_LOOPS=1024 -DHAVE_GETHOSTBYNAME2 -DHAVE_UNION_SEMUN -DHAVE_SCHED_YIELD -DHAVE_MSG_NOSIGNAL -DHAVE_MSGHDR_MSG_CONTROL -DHAVE_ALLOCA_H -DHAVE_TIMEGM -DHAVE_EPOLL -DHAVE_SIGIO_RT -DHAVE_SELECT  -c identity.c -o identity.o
identity.c: In function ‘addIdentity’:
identity.c:834:13: error: storage size of ‘ctx’ isn’t known
  EVP_MD_CTX ctx;
             ^~~
identity.c:854:3: warning: implicit declaration of function ‘EVP_MD_CTX_cleanup’ [-Wimplicit-function-declaration]
   EVP_MD_CTX_cleanup(&ctx);
   ^~~~~~~~~~~~~~~~~~
identity.c:834:13: warning: unused variable ‘ctx’ [-Wunused-variable]
  EVP_MD_CTX ctx;
             ^~~
identity.c: In function ‘checkAuthority’:
identity.c:1193:15: error: dereferencing pointer to incomplete type ‘X509_EXTENSION {aka struct X509_extension_st}’
    data = cext->value->data;
               ^~
identity.c: In function ‘checkSign’:
identity.c:1254:13: error: storage size of ‘ctx’ isn’t known
  EVP_MD_CTX ctx;
             ^~~
identity.c:1254:13: warning: unused variable ‘ctx’ [-Wunused-variable]
In file included from ../../parser/../ip_addr.h:46:0,
                 from ../../parser/msg_parser.h:48,
                 from ../../sr_module.h:48,
                 from identity.c:98:
identity.c: In function ‘verify_callback’:
identity.c:1719:38: error: dereferencing pointer to incomplete type ‘X509_STORE_CTX {aka struct x509_store_ctx_st}’
    X509_verify_cert_error_string(stor->error));
                                      ^
../../parser/../dprint.h:336:33: note: in definition of macro ‘MY_DPRINT’
      dp_my_pid(), __DP_FUNC, ## args) \
                                 ^~~~
identity.c:1718:3: note: in expansion of macro ‘LM_INFO’
   LM_INFO("certificate validation failed: %s\n",
   ^~~~~~~

**Comment by razvancrainea** [comment]
Thanks for reporting it. Please try the latest version now.

**Comment by ppisar** [comment]
Now it builds. Thank you.

**Comment by razvancrainea** [comment]
This was fixed in the newer versions; will not downgrade it. Closing this ticket.
