### ISSUE TITLE
sngtc module does not compile in 2.3 and 2.4 

### ISSUE THREAD

**Issue by cbsergiocf** [OpenSIPS/opensips#1392]
There are a couple of compiling issues related to LM_GEN1 invocation and it seems that the sdp structure in the msg_sip object has change and does not compile.

- sngtc.c: In function ‘sng_logger’:
**sngtc.c:414:18: error: expected ‘)’ before ‘fmt’**
    LM_GEN1(L_DBG, fmt, args);

- sngtc.c: In function ‘sngtc_callee_answer’:
**sngtc.c:1319:26: error: ‘struct sip_msg’ has no member named ‘sdp’**
                       msg->sdp->sessions);

**Comment by cbsergiocf** [comment]
Thx!

**Comment by cbsergiocf** [comment]
Now it fails to compile with different error ...please find attached error log
[sngtc-errors.txt](https://github.com/OpenSIPS/opensips/files/2106911/sngtc-errors.txt)

**Comment by cbsergiocf** [comment]
Thx @liviuchircu  now works!
