### ISSUE TITLE
[BUG] Build regression in 50c406bc4fd4975c63f5754a8bcdc49d3fa80876 on *BSD

### ISSUE THREAD

**Issue by DamjanJovanovic** [OpenSIPS/opensips#3689]
**OpenSIPS version you are running**
git master

**Describe the bug**
Compiling opensips on FreeBSD fails because of multiple errors like:
```
gmake[1]: Entering directory '/opensips/modules/db_unixodbc'
In file included from db_con.c:32:
./db_con.h:39:10: fatal error: 'sql.h' file not found
   39 | #include <sql.h>
      |          ^~~~~~~
In file included from dbase.c:38:
./val.h:35:10: fatal error: 'sql.h' file not found
   35 | #include <sql.h>
      |          ^~~~~~~1 error generated.

In file included from row.c:34:
./val.h:35:10: fatal error: 'sql.h' file not found
   35 | #include <sql.h>
      |          ^~~~~~~
1 error generated.
```

**To Reproduce**
gmake prefix=/opt/opensips include_modules="tls_mgm tls_openssl proto_tls db_unixodbc" modules

**Expected behavior**
A successful build.

**Relevant System Logs**

**OS/environment information**
 - Operating System: FreeBSD 14.3
 - OpenSIPS installation: git master
 - other relevant information:

**Additional context**
A simple way to work around the issue:
```
diff --git a/modules/db_unixodbc/Makefile b/modules/db_unixodbc/Makefile
index f484b3900..d8d1c6ee8 100644
--- a/modules/db_unixodbc/Makefile
+++ b/modules/db_unixodbc/Makefile
@@ -4,7 +4,7 @@ include ../../Makefile.defs
 auto_gen=
 NAME=db_unixodbc.so
 
-ifeq ($(CROSS_COMPILE),)
+ifneq ($(CROSS_COMPILE),)
 LIBS += -lodbc
 else
 # sql.h locations (freebsd,openbsd  solaris)
```

Many other modules give warnings like:
gmake[1]: --cflags: No such file or directory
gmake[1]: --libs: No such file or directory

I don't know what 50c406bc4fd4975c63f5754a8bcdc49d3fa80876 did or why, but it definitely broke FreeBSD instead of fixing it. The intention was apparently to fix the (now obsolete) kFreeBSD, but it seems to have only made FreeBSD building worse. Maybe the "ifeq ($(CROSS_COMPILE),)" should be replaced with "if kFreeBSD"?
